import user from './assets/default_user.jpg'
import user2 from './assets/default_user2.jpg'
import user3 from './assets/default_user3.jpg'
import user4 from './assets/default_user4.jpg'

export const userSalesData = [
  {
    name: 'Jan',
    'Active User': 4000,
    pv: 2400,
    amt: 2400,
  },
  {
    name: 'Feb',
    'Active User': 3000,
    pv: 1398,
    amt: 2210,
  },
  {
    name: 'Mar',
    'Active User': 2000,
    pv: 9800,
    amt: 2290,
  },
  {
    name: 'Apr',
    'Active User': 2780,
    pv: 3908,
    amt: 2000,
  },
  {
    name: 'May',
    'Active User': 1890,
    pv: 4800,
    amt: 2181,
  },
  {
    name: 'Jun',
    'Active User': 2390,
    pv: 3800,
    amt: 2500,
  },
  {
    name: 'Jul',
    'Active User': 1234,
    pv: 4300,
    amt: 2100,
  },
  {
    name: 'Aug',
    'Active User': 6610,
    pv: 4300,
    amt: 2100,
  },
  {
    name: 'Sep',
    'Active User': 3490,
    pv: 4300,
    amt: 2100,
  },
  {
    name: 'Oct',
    'Active User': 3410,
    pv: 4300,
    amt: 2100,
  },
  {
    name: 'Nov',
    'Active User': 5590,
    pv: 4300,
    amt: 2100,
  },
  {
    name: 'Dec',
    'Active User': 2390,
    pv: 4300,
    amt: 2100,
  },
]

export const usersDetail = [
  {
    id: 1,
    username: 'John Snow',
    avatar: user,
    email: 'John@example.com',
    status: 'active',
    transactions: '$123.90',
  },
  {
    id: 2,
    username: 'John Snow',
    avatar: user2,
    email: 'John@example.com',
    status: 'active',
    transactions: '$123.90',
  },
  {
    id: 3,
    username: 'John Snow',
    avatar: user,
    email: 'John@example.com',
    status: 'active',
    transactions: '$123.90',
  },
  {
    id: 4,
    username: 'John Snow',
    avatar: user3,
    email: 'John@example.com',
    status: 'active',
    transactions: '$123.90',
  },
  {
    id: 5,
    username: 'John Snow',
    avatar: user,
    email: 'John@example.com',
    status: 'active',
    transactions: '$123.90',
  },
  {
    id: 6,
    username: 'John Snow',
    avatar: user3,
    email: 'John@example.com',
    status: 'active',
    transactions: '$123.90',
  },
  {
    id: 7,
    username: 'John Snow',
    avatar: user2,
    email: 'John@example.com',
    status: 'active',
    transactions: '$123.90',
  },
  {
    id: 8,
    username: 'John Snow',
    avatar: user,
    email: 'John@example.com',
    status: 'active',
    transactions: '$123.90',
  },
  {
    id: 9,
    username: 'John Snow',
    avatar: user,
    email: 'John@example.com',
    status: 'active',
    transactions: '$123.90',
  },
  {
    id: 10,
    username: 'John Snow',
    avatar: user4,
    email: 'John@example.com',
    status: 'active',
    transactions: '$123.90',
  },
]

export const productSalesData = [
  {
    name: 'Jan',
    Sales: 1850,
    pv: 2400,
    amt: 5400,
  },
  {
    name: 'Feb',
    Sales: 3225,
    pv: 1398,
    amt: 2210,
  },
  {
    name: 'Mar',
    Sales: 3400,
    pv: 3400,
    amt: 2290,
  },
]

export const productsDetail = [
  {
    id: 1,
    name: 'Dangote 3X',
    image: user2,
    stock: 123,
    status: 'active',
    price: '$123.90',
  },
  {
    id: 2,
    name: 'Dangote 3X',
    image: user2,
    stock: 123,
    status: 'active',
    price: '$123.90',
  },
  {
    id: 3,
    name: 'Dangote 3X',
    image: user2,
    stock: 123,
    status: 'active',
    price: '$123.90',
  },
  {
    id: 4,
    name: 'Dangote 3X',
    image: user2,
    stock: 123,
    status: 'active',
    price: '$123.90',
  },
  {
    id: 5,
    name: 'Dangote 3X',
    image: user2,
    stock: 123,
    status: 'active',
    price: '$123.90',
  },
  {
    id: 6,
    name: 'Dangote 3X',
    image: user2,
    stock: 123,
    status: 'active',
    price: '$709.90',
  },
  {
    id: 7,
    name: 'Dangote 3X',
    image: user2,
    stock: 123,
    status: 'active',
    price: '$123.90',
  },
  {
    id: 8,
    name: 'Dangote 3X',
    image: user2,
    stock: 123,
    status: 'active',
    price: '$524.90',
  },
  {
    id: 9,
    name: 'GDAF',
    image: user2,
    stock: 123,
    status: 'active',
    price: '$123.90',
  },
  {
    id: 10,
    name: 'Dangote 3X',
    image: user2,
    stock: 123,
    status: 'active',
    price: '$123.90',
  },
]
